# Generated by Django 6.0.2 on 2026-04-18 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quality', models.CharField(blank=True, choices=[('low', 'Low quality / discard'), ('sparse', 'Sparse - needs follow-up'), ('rich', 'Rich - usable for MCQ')], max_length=10, null=True)),
                ('followup_prompt', models.TextField(blank=True, null=True)),
                ('enrichment', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='inputinfopage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='inputinfopage',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputinfopage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inputinfopage',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('personal', 'Personal Info'), ('family', 'Family'), ('education', 'Education'), ('diary', 'Diary / Recent Events')], default='personal', max_length=20)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('free_recall', 'Free Recall')], default='mcq', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_diary_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='core.diaryentry')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='core.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='core.patientprofile'),
        ),
        migrations.CreateModel(
            name='AIquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interview', to='core.patientprofile')),
            ],
        ),
        migrations.AddField(
            model_name='inputinfopage',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.patientprofile'),
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.generatedquestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
