# Generated by Django 6.0.2 on 2026-04-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    # 0001_initial already contains the models and fields that this migration
    # previously tried to create again, which broke fresh test database setup.
    operations = []
