# Generated by Django 6.0.2 on 2026-04-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_diaryentry_alter_inputinfopage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputinfopage",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
    ]
