# Generated by Django 6.0.2 on 2026-04-18 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiquestions_diaryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('personal', 'Personal Info'), ('family', 'Family'), ('education', 'Education'), ('diary', 'Diary / Recent Events')], default='personal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='core.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
