# Generated by Django 6.0.2 on 2026-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_inputinfopage_is_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedquestion",
            name="tone_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="generatedquestion",
            name="tone_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
