# Generated by Django 6.0.2 on 2026-04-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_generatedquestion_tone_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedquestion",
            name="last_reprompted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedquestion",
            name="reprompt_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
