# Generated by Django 6.0.2 on 2026-04-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_generatedquestion_reprompt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputinfopage',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal Info'), ('family', 'Family Info'), ('custom', 'Custom')], default='personal', max_length=20),
        ),
    ]
