# Generated by Django 6.0.2 on 2026-04-26 22:38

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inputinfopage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiceline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=core.models.voiceline_upload_path)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voiceline', to='core.inputinfopage')),
            ],
        ),
    ]
